// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwKFeqcmrN6v9KJRbPHmlPB68-Y7vsTBA',
    appId: '1:726175851822:android:828fee2246715441ac46bf',
    messagingSenderId: '726175851822',
    projectId: 'expenser-bc977',
    storageBucket: 'expenser-bc977.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSgykHzDXdR-FO2RPu9saVWv32qJZMTT8',
    appId: '1:726175851822:ios:05a42de32143f376ac46bf',
    messagingSenderId: '726175851822',
    projectId: 'expenser-bc977',
    storageBucket: 'expenser-bc977.firebasestorage.app',
    iosClientId: '726175851822-ldkff64ll4baq0nfsupi9f2b87nkj4qq.apps.googleusercontent.com',
    iosBundleId: 'com.kksystems.expenser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSgykHzDXdR-FO2RPu9saVWv32qJZMTT8',
    appId: '1:726175851822:ios:05a42de32143f376ac46bf',
    messagingSenderId: '726175851822',
    projectId: 'expenser-bc977',
    storageBucket: 'expenser-bc977.firebasestorage.app',
    iosClientId: '726175851822-ldkff64ll4baq0nfsupi9f2b87nkj4qq.apps.googleusercontent.com',
    iosBundleId: 'com.kksystems.expenser',
  );
}
